import './styles.scss'

const MainText = () => {
	return <div className='main-text'>
		Базовый текст о том, зачем эта ассоциация
		<p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad alias cupiditate dignissimos expedita impedit labore quaerat quia quibusdam rerum! Consequuntur ipsa quia quisquam. Ea eligendi impedit iusto non possimus voluptatum?</span><span>Accusantium aperiam consectetur consequatur deleniti eos eveniet facilis, fugiat, fugit labore magnam neque nulla obcaecati pariatur praesentium quam quia quidem rerum sit, velit voluptate? Debitis ea esse explicabo ipsa nostrum.</span><span>Architecto debitis eligendi facere minus nesciunt odio pariatur similique, sit. Aut consequatur debitis excepturi, fugiat ipsam rerum similique voluptatem? Atque, consectetur explicabo nostrum perspiciatis quod rerum tenetur. Aperiam, dolorum sed.</span><span>Animi blanditiis cupiditate illum magnam nobis nostrum officiis pariatur, reprehenderit ut voluptatibus? Autem blanditiis maxime sunt. Adipisci, commodi ex exercitationem facilis fuga nihil quasi temporibus? Alias impedit in sunt voluptatibus?</span><span>Ab at cumque illum libero maxime nemo qui sed suscipit voluptatem voluptates. Autem cupiditate, ea eveniet illum maiores molestiae nulla officiis, perferendis possimus quia repellendus saepe suscipit tempora, velit vero.</span><span>Dicta eaque eum explicabo laboriosam natus nisi porro quam soluta. Assumenda deserunt ducimus ipsam, nobis placeat provident reiciendis tempora? Assumenda magni necessitatibus nisi nobis soluta veniam veritatis voluptatum! Unde, velit!</span><span>A id nostrum saepe tenetur. Adipisci asperiores at culpa esse excepturi id in laborum libero magnam maxime molestiae molestias nam, neque nihil omnis, perspiciatis quas quo suscipit ullam veniam veritatis!</span><span>Assumenda deleniti dolore earum eum harum id libero natus nemo nihil officiis provident quam, quibusdam rem sed, totam. Delectus eligendi exercitationem pariatur perferendis placeat porro rem repellendus. Quo, sequi, velit?</span><span>Aut blanditiis culpa cumque deleniti doloribus eveniet expedita explicabo fuga fugiat id ipsam iste magni maiores molestias natus nemo nostrum odio, quam quasi quia quod recusandae sit soluta unde veniam!</span><span>Atque modi officiis qui reiciendis. Alias, earum eligendi. Alias asperiores deleniti dicta dolores, eius eum id ipsa, iste iusto, magnam nobis pariatur perspiciatis quidem vitae voluptatem voluptates voluptatum. Delectus, tempora?</span>
		</p>
	</div>;
}
export default MainText